system:
  ip: 127.0.0.1
  port: 8080
log:
  app: blogx_server
  dir: logs
jwt:
  secret: secret
  expire: 3
  issuer: zh
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: blogx
  source: mysql
  debug: false
db1:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: blogx
  source: mysql
  debug: false
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 2