system:
  ip: 127.0.0.1
  port: 8080
log:
  app: blogx_server
  dir: logs
jwt:
  secret: secret
  expire: 3
  issuer: zh
upload:
  size: 3
  whiteList:
    - jpg
    - jpeg
    - png
    - webp
    - gif
  uploadDir: image
qiNiu:
  enable: true
  accessKey: _jkOeY4joRduqaoTXliBNOyO2dFIrT4X6WxIIjGG
  secretKey: iKmeH1OZyVNOOYm2FB0K05cxyw8gBHuMH2wNcXpd
  bucket: zhdeblog
  uri: https://szlbam6vv.hn-bkt.clouddn.com
  region: z2
  prefix: blogx
  size: 3
  expiry: 60
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: blogx
  source: mysql
  debug: false
db1:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: blogx
  source: mysql
  debug: false
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 2